### ISSUE TITLE
Coarse-graining bug in HeatTransferGunn and HeatTransferRanzMarshall

### ISSUE THREAD

**Issue by CHuang-Go** [ParticulateFlow/CFDEMcoupling-PFM#1]
# coarse-graining factors not overwritten if the CoarseGrainingFactors is not specified in propDict.

So in the BeetstraDrag, if the CoarseGrainingFactors is not specified in the couplingProperties, the coarse-graining value will be overwritten by the value specified in LIGGGHTS.

BeetstraDrag.C line 149-158
```   
    if (typeCG_.size()>1 || typeCG_[0] > 1)
    {
        Info << "Beetstra using scale = " << typeCG_ << endl;
    }
    else if (particleCloud_.cg() > 1)
    {
        scaleDia_=particleCloud_.cg();
        typeCG_[0] = scaleDia_;
        Info << "Beetstra using scale from liggghts cg = " << scaleDia_ << endl;
    }
```

In both heatTransfer models, the `typeCG_[0]` is not overwritten. Only the scaledDia_ is updated, however, it is not used during the calculation of the heat transfer coefficient. Suggest to add the same line as in BeetstraDrag ` typeCG_[0] = scaleDia_` to correct this.

**Comment by danielque** [comment]
Will take a look, thanks for reporting.
