### ISSUE TITLE
Problem with Installation of CFDEM on University HPC

### ISSUE THREAD

**Issue by shaikasif808** [ParticulateFlow/CFDEMcoupling-PFM#11]
Hi, 
I am trying to install the CFDEM on the TUHH HPC cluster but I am getting the following error. 

1. After cloning with LIGGGHTS-PFM repo, I created an src-build folder.
2. By using the ccmake ../src ; I updated the CMAKE_BUILD_TYP to release
3. After running make -j from src-build I am getting this warning message at end:
4. 
![image](https://github.com/ParticulateFlow/CFDEMcoupling-PFM/assets/75698631/dfcc09f8-d0b4-4c4e-ba62-4ce28b8c42ec)
5. On HPC only vtk 8.0.1 version module is available and when I checked for the dependencies of this file, I found that linmpi.so.20 is missing.
6. 
![image](https://github.com/ParticulateFlow/CFDEMcoupling-PFM/assets/75698631/5537c4ed-2155-436c-8789-e7c14bcdcbba)

At the end the log_compilation_is_fail, Is it due to the vtk missing dependency or HPC problem. 

Regards
Asif

**Comment by simonPFM** [comment]
Hi Asif, 
does your university HPC support singularity/docker images?
Regards, 
Simon

**Comment by shaikasif808** [comment]
Dear Simon, 
On TUHH HPC we load the module from the list of available modules via bashrc.

I am new to using the HPC, so I was unable to find out if HPC is using the docker or singularity.

**Comment by simonPFM** [comment]
Ok, maybe you ask your system administrator. In case that singularity or docker are available, I can provide proper images for LIGGGHTS and CFDEMcoupling, which allow their use on different architectures.

**Comment by shaikasif808** [comment]
Sure, I will get in touch with the HPC admin and get this info. 

Once again thank you very much for your help.

**Comment by shaikasif808** [comment]
Hi Simon, 
The HPC does not support the singularity or docker image. 

Luckily, we found the solution and now CFDEM is running on our HPC. 

There was a problem with VTK module 8.0.1 and now we downgraded it to VTK 7.1.1, which is a more compatible version for LIGGGHTS and OpenFOAM 6. 

Once again thank you very much for your response :)
