### ISSUE TITLE
MPIRUN

### ISSUE THREAD

**Issue by Li-Ben512** [ParticulateFlow/CFDEMcoupling-PFM#13]
Hello，everyone. 

I have successfully compiled CDFEM (OpenFoam 5.x, Liggghts 3.8), but there are still a problem when running multiphase case, eg dambreak. I try to modify openmpi, etc., but no effect. Any help? Thank you.

Lee

```
//   run_parallel_cfdemSolverMultiphase_test   //

/home/lee/CFDEM/CFDEMcoupling/tutorials/cfdemSolverMultiphase/damBreak/CFD

rm: cannot remove 'couplingFiles/*': No such file or directory
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       ubuntu
Executable: cfdemSolverMultiphase
```

**Comment by danielque** [comment]
CFDEMcoupling-PFM  only works correctly in combination with LIGGGHTS-PFM, not  Liggghts 3.8.

**Comment by Li-Ben512** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello Danicl
        Thank you for your help.The above is a writting error , and I am using LIGGGHTS_PFM from github. The enviroment variables setting were abided by maual. I  am going to reinstall it. Lee
    
        
            
        
    
    
        
        

        
    

    On 8/2/2024 ***@***.***> wroteCFDEMcoupling-PFM  only works correctly in combination with LIGGGHTS-PFM, not  Liggghts 3.8.

**Comment by Li-Ben512** [comment]
> CFDEMcoupling-PFM only works correctly in combination with LIGGGHTS-PFM, not Liggghts 3.8.

Hello Danicl

Thank you for your help. The above is a writing error , and I am using LIGGGHTS_PFM from github. The environment variables setting were abided by manual. I  am going to reinstall it. 

Lee

**Comment by Li-Ben512** [comment]
The cfdemmultiphase case could run after reinstalling, but only in  the the terminal that compiling CFDEMcoupling. If closing and opening anohter terminal, the error will occur.

mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       ubuntu
Executable: liggghts

**Comment by Li-Ben512** [comment]
> CFDEMcoupling-PFM only works correctly in combination with LIGGGHTS-PFM, not Liggghts 3.8.

The cfdemmultiphase case could run after reinstalling, but only in the the terminal that compiling CFDEMcoupling. If closing and opening anohter terminal, the error will occur again.

mpirun was unable to find the specified executable file, and therefore
did not launch the job. This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
line parameter option (remember that mpirun interprets the first
unrecognized command line token as the executable).

Node: ubuntu
Executable: liggghts

**Comment by danielque** [comment]
You mostly likely did not add the sourcing of the CFDEMcoupling bashrc file to your global .bashrc file.
If you don't want to execute
`source ~/CFDEM/CFDEMcoupling/etc/bashrc`
each time you open a new terminal, you need to add a corresponding line to your global .bashrc file (like it's describe for OpenFOAM in the manual)

**Comment by Li-Ben512** [comment]
> You mostly likely did not add the sourcing of the CFDEMcoupling bashrc file to your global .bashrc file. If you don't want to execute `source ~/CFDEM/CFDEMcoupling/etc/bashrc` each time you open a new terminal, you need to add a corresponding line to your global .bashrc file (like it's describe for OpenFOAM in the manual)

Thank you very much for your help. The problem is by the environment variables,  and I have successfully ran the code. Thanks again!
