### ISSUE TITLE
Compilation of solvers needs link to python

### ISSUE THREAD

**Issue by kolarji2** [ParticulateFlow/CFDEMcoupling-PFM#2]
When I tried to compile solvers with cfdemCompCFDEMsol, it was necessary to link to python. Otherwise, I got many compile errors from libvtkPython***, undefined references. One example is below:
`/usr/bin/ld: /usr/lib/libvtkPythonContext2D.so.1: undefined reference to `_Py_Dealloc'`

```
Archlinux 2022.1.1.
gcc (GCC) 11.1.0
cmake version 3.22.2
python3.10
OpenFOAM-6
vtk 9.1
```

Maybe it was just my issue. But otherwise, it would be nice to include it in the build configuration, so it is not necessary to do it manually.

# paths for additional libraries (etc/additionalLibs)
CFDEM_ADD_LIB_PATHS = -I/usr/include/python3.10 -lpython3.10

**Comment by danielque** [comment]
That's most probably a python2 vs python3 issue, where CFDEMcoupling is expecting python2.
