### ISSUE TITLE
Problem about Multiphase

### ISSUE THREAD

**Issue by yfun0815** [ParticulateFlow/CFDEMcoupling-PFM#7]
Hello everyone,
I have completely installed OpenFOAM 6 and CFDEM. I want to run the Multiphase dam break case. But I encountered the fault like below:

//   run_parallel_cfdemSolverMultiphase_test   //

/home/fanyi/CFDEM/CFDEMcoupling/tutorials/cfdemSolverMultiphase/damBreak/CFD

rm: cannot remove 'couplingFiles/*': No such file or directory

--> FOAM FATAL ERROR:
cfdemSolverMultiphase requires OpenFOAM 4.x or 5.x to work properly

FOAM exiting

It seems whether I need to install OpenFOAM 5.x again. How I can link to CFDEM?
Thanks!

Regards,
Fan

**Comment by danielque** [comment]
As the error message tells you, the multiphase solver requires linking against OpenFOAM 4.x or 5.x to work properly as it has some issues in version 6.
